import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Simple Notes",
  description: "Generated by M1lo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
